name: Docker Branch Deploy

on:
  pull_request:
    branches:
      - "main"
    types: [labeled, opened, reopened, synchronize]
  pull_request_review:
    types: [submitted]

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'deploy-dev')
    steps:
      - run: "echo 'association: ${{github.event.pull_request.author_association}}'"
      - run: "echo 'head ref: ${{github.event.pull_request.head.ref}}'"
